#!/usr/bin/env python
import argparse
import subprocess
import tempfile
import json
import csv
import sys
import os
import shutil

STATUS = "status"
BOOTED = "booted"
ROLLBACK = "rollback"
STAGED = "staged"
COMPOSEFS = "composefs"
IMAGE="image"
VERITY = "verity"
VERSION = "version"

# /etc/os-release stuff
OS_VERSION_ID="VERSION_ID"
OS_ID="ID"

DEFAULT_SCRIPT_LOCATION="/etc/overlay-ext/build.sh"
BASE_EXT_NAME="overlay-ext"
EXT_DEST="/var/lib/extensions"

parser = argparse.ArgumentParser(description="Build a deployment-locked sysext out of a shell script. Builds against the booted and staged deployments by default.")
parser.add_argument("script", default=DEFAULT_SCRIPT_LOCATION, nargs="?", help="filename of script to use")
parser.add_argument("-f", "--force", help="rebuild each deployment's overlay even if it already exists (e.g. to update it with new changes)", action="store_true")
parser.add_argument("-c", "--clean", help=f"remove all extensions built by this script from {EXT_DEST}", action="store_true")

args = parser.parse_args(sys.argv[1:])

# Helpful function to exit with an error message without providing a full stack trace
def exit_message(message):
    print(message)
    sys.exit()


# Complain about bootc status returning unexpected data
def invalid_format(status, key):
    exit_message("Error: Output of 'bootc status' was formatted unexpectedly - key \"{key}\" was missing. Output was:\n{status}".format(key=key, status=json.dumps(status, indent=4)))


# Actually build the sysext
def build_sysext(deployment_details, script_name, force=False):
    # Make sure we have the info we need here
    if VERITY not in deployment_details[COMPOSEFS]:
        invalid_format(deployment_details, VERITY)
        return

    if VERSION not in deployment_details[IMAGE]:
        invalid_format(deployment_details, VERSION)
        return

    deployment_verity = deployment_details[COMPOSEFS][VERITY]
    deployment_version = deployment_details[IMAGE][VERSION]
    
    # Name the extension after the deployment version
    ext_name = f"{BASE_EXT_NAME}.{deployment_version}"

    # If the extension has already been built on this deployment, only rebuild it if force rebuilding.
    if os.path.isdir(f"{EXT_DEST}/{ext_name}") and not force:
        print(f"Skipping extension {ext_name} because it has already been built for the deployment {deployment_version}. Use --force to rebuild this if you want to update it.")
        return

    # Use a randomly generated tmp directory
    with tempfile.TemporaryDirectory() as temp_dir:
        WORK_PATH = temp_dir

        # Create working directories
        for directory in (ext_name, "work", "merged"):
            os.makedirs(f"{WORK_PATH}/{directory}", exist_ok=True)

        # Mount the deployment
        subprocess.run(
            [
                "bootc",
                "internals",
                "cfs",
                "mount",
                deployment_verity,
                f"{WORK_PATH}/merged",
                f"--upperdir={WORK_PATH}/{ext_name}",
                f"--workdir={WORK_PATH}/work",
                "--read-write",
            ],
            check=True,
        )

        # Copy the script into the mountpoint and run it in a systemd-nspawn container
        generator_path = f"{WORK_PATH}/merged/generator.sh"
        shutil.copy(script_name, generator_path)
        os.chmod(generator_path, 0o700)
        subprocess.run(
            [
                "systemd-nspawn",
                "-D",
                f"{WORK_PATH}/merged",
                "--resolv-conf=bind-uplink",
                "bash",
                "-c",
                "/generator.sh",
            ],
            check=True,
        )

        # Remove all directories other than the /usr tree and create sysext directories
        with os.scandir(f"{WORK_PATH}/{ext_name}") as entries:
            for entry in entries:
                if entry.name == "usr":
                    continue
                if entry.is_dir(follow_symlinks=False):
                    shutil.rmtree(entry.path)
                else:
                    os.remove(entry.path)
        os.makedirs(f"{WORK_PATH}/{ext_name}/usr/lib/extension-release.d", exist_ok=True)

        # Load /etc/os-release and check it has the info we need
        os_info = {}
        try:
            with open(f"{WORK_PATH}/merged/etc/os-release", "r") as os_release_file:
                os_info = dict(csv.reader(os_release_file, delimiter="="))

        except FileNotFoundError:
            pass

        # If the dict is empty, something went wrong
        if not bool(os_info):
            print(f"Error: Could not find /etc/os-release on the deployment {deployment_version}")

        # Do not proceed if /etc/os-release is missing the flags sysexts rely on
        elif OS_VERSION_ID not in os_info or OS_ID not in os_info:
            print(f"Error: /etc/os-release is missing the required flags: {OS_VERSION_ID}=, {OS_ID}=")

        else:
            os_id = os_info[OS_ID]
            os_version_id = os_info[OS_VERSION_ID]

            # Write to the file 
            with open(f"{WORK_PATH}/{ext_name}/usr/lib/extension-release.d/extension-release.{ext_name}", "w+") as extension_release:
                extension_release.write(f'{OS_ID}="{os_id}"\n{OS_VERSION_ID}="{os_version_id}"')

            # Remove a previous version of the extension then copy the new version instead
            try:
                shutil.rmtree(f"{EXT_DEST}/{ext_name}")
            except FileNotFoundError:
                pass
            shutil.copytree(f"{WORK_PATH}/{ext_name}", EXT_DEST, symlinks=True)
            subprocess.run(["systemd-sysext", "refresh"], check=True)

        subprocess.run(["umount", f"{WORK_PATH}/merged"], check=True)


# Run the script on a specified deployment
def build_for_deployment(images, deployment_name, error_on_no_exist=True, force=False):
    if deployment_name in images and images[deployment_name] is not None and COMPOSEFS in images[deployment_name] and IMAGE in images[deployment_name]:
        build_sysext(images[deployment_name], args.script, force=force)

    elif error_on_no_exist:
        invalid_format(bootc_status, deployment_name)


# Clean up all files this script generated and exit
if args.clean:
    # Only remove extensions which are named overlay-ext.[version] so as not to mess with other sysexts the user may have
    with os.scandir(EXT_DEST) as entries:
        for entry in entries:
            if entry.name.startswith(f"{BASE_EXT_NAME}."):
                os.remove(entry.path)
    subprocess.run(["systemd-sysext", "refresh"], check=True)
    exit_message(f"Cleaned up all generated extensions in {EXT_DEST}")

# Do not allow running by an unprivileged user as root is required for commands such as "bootc status"
if os.geteuid() != 0:
    exit_message("Error: Must be run as root!")


# First we check the script actually exists as a valid file
try:
    script_contents = open(args.script, "r").read()

except FileNotFoundError:
    exit_message(f"Error: File \"{args.script}\" could not be found.")


# Then that bash can execute it
try:
    subprocess.run(["bash", "-n", args.script], check=True, capture_output=True)
except subprocess.CalledProcessError:
    exit_message(f"Error: File \"{args.script}\" is not a valid bash script - use \"bash -n {args.script}\" to validate it.")


# Check bootc status so we can find the verity hashes of the images
bootc_status = json.loads(
    subprocess.run(["bootc", "status", "--json"], check=True, capture_output=True).stdout
)
images = None

# Look for the list of images
if STATUS in bootc_status:
    images = bootc_status[STATUS]

else:
    invalid_format(bootc_status, STATUS)


build_for_deployment(images, BOOTED, error_on_no_exist=True, force=args.force)
build_for_deployment(images, STAGED, error_on_no_exist=False, force=args.force)
