#!/usr/bin/env python
import argparse
import subprocess
import tempfile
import json
import csv
import sys
import os

ENCODING_TYPE="UTF-8"

STATUS = "status"
BOOTED = "booted"
ROLLBACK = "rollback"
STAGED = "staged"
COMPOSEFS = "composefs"
IMAGE="image"
VERITY = "verity"
VERSION = "version"

# /etc/os-release stuff
OS_VERSION_ID="VERSION_ID"
OS_ID="ID"

BASE_EXT_NAME="overlay-ext"
EXT_DEST="/var/lib/extensions"

parser = argparse.ArgumentParser(description="Build a deployment-locked sysext out of a shell script. Builds against the booted and staged deployments by default.")
parser.add_argument("script", default=None, nargs="?", help="filename of script to use")
parser.add_argument("-f", "--force", help="rebuild the current deployment's overlay even if it already exists", action="store_true")
parser.add_argument("-c", "--clean", help=f"remove all extensions built by this script from {EXT_DEST}", action="store_true")

args = parser.parse_args(sys.argv[1:])

# Helpful function to exit with an error message without providing a full stack trace
def exit_message(message):
    print(message)
    sys.exit()


# Complain about bootc status returning unexpected data
def invalid_format(status, key):
    exit_message("Error: Output of 'bootc status' was formatted unexpectedly - key \"{key}\" was missing. Output was:\n{status}".format(key=key, status=json.dumps(status, indent=4)))


# Actually build the sysext
def build_sysext(deployment_details, script_name, force=False):
    # Make sure we have the info we need here
    if VERITY not in deployment_details[COMPOSEFS]:
        invalid_format(deployment_details, VERITY)
        return

    if VERSION not in deployment_details[IMAGE]:
        invalid_format(deployment_details, VERSION)
        return

    deployment_verity = deployment_details[COMPOSEFS][VERITY]
    deployment_version = deployment_details[IMAGE][VERSION]
    
    # Name the extension after the deployment version
    ext_name = f"{BASE_EXT_NAME}.{deployment_version}"

    # If the extension has already been built on this deployment, only rebuild it if force rebuilding.
    if os.path.isdir(f"{EXT_DEST}/{ext_name}") and not force:
        print(f"Skipping extension {ext_name} because it has already been built for the current deployment. Use --force to rebuild this if you want to update it.")
        return

    # Use a randomly generated tmp directory
    with tempfile.TemporaryDirectory() as temp_dir:
        WORK_PATH = temp_dir

        # Create working directories
        subprocess.run(f"mkdir -p {WORK_PATH}/{{{ext_name},work,merged}}", shell=True)

        # Mount the deployment
        subprocess.run(f"bootc internals cfs mount {deployment_verity} {WORK_PATH}/merged --upperdir={WORK_PATH}/{ext_name} --workdir={WORK_PATH}/work --read-write", shell=True)

        # Copy the script into the mountpoint and run it in a systemd-nspawn container
        subprocess.run(f"cp {script_name} {WORK_PATH}/merged/generator.sh; chmod +x {WORK_PATH}/merged/generator.sh", shell=True)
        subprocess.run(f"systemd-nspawn -D {WORK_PATH}/merged --resolv-conf=bind-uplink bash -c \"/generator.sh\"", shell=True)

        # Remove all directories other than the /usr tree and create sysext directories
        subprocess.run(f"cd {WORK_PATH} && find {ext_name} -mindepth 1 -maxdepth 1 ! -name \"usr\" -exec rm -rf {{}} +", shell=True)
        subprocess.run(f"mkdir -p {WORK_PATH}/{ext_name}/usr/lib/extension-release.d/", shell=True)

        # Load /etc/os-release and check it has the info we need
        os_info = {}
        try:
            with open(f"{WORK_PATH}/merged/etc/os-release", "r") as os_release_file:
                os_info = dict(csv.reader(os_release_file, delimiter="="))

        except FileNotFoundError:
            pass

        # If the dict is empty, something went wrong
        if not bool(os_info):
            print(f"Error: Could not find /etc/os-release on the deployment {deployment_version}")

        # Do not proceed if /etc/os-release is missing the flags sysexts rely on
        elif OS_VERSION_ID not in os_info or OS_ID not in os_info:
            print(f"Error: /etc/os-release is missing the required flags: {OS_VERSION_ID}=, {OS_ID}=")

        else:
            os_id = os_info[OS_ID]
            os_version_id = os_info[OS_VERSION_ID]

            # Write to the file 
            with open(f"{WORK_PATH}/{ext_name}/usr/lib/extension-release.d/extension-release.{ext_name}", "w+") as extension_release:
                extension_release.write(f'{OS_ID}="{os_id}"\n{OS_VERSION_ID}="{os_version_id}"')

            # Remove a previous version of the extension then copy the new version instead
            subprocess.run(f"rm -rf {EXT_DEST}/{ext_name}; cp -r {WORK_PATH}/{ext_name} {EXT_DEST}; systemd-sysext refresh", shell=True)

        subprocess.run(f"umount {WORK_PATH}/merged", shell=True)


# Run the script on a specified deployment
def build_for_deployment(images, deployment_name, error_on_no_exist=True, force=False):
    if deployment_name in images and images[deployment_name] is not None and COMPOSEFS in images[deployment_name] and IMAGE in images[deployment_name]:
        build_sysext(images[deployment_name], args.script, force=force)

    elif error_on_no_exist:
        invalid_format(bootc_status, deployment_name)


# Clean up all files this script generated and exit
if args.clean:
    # Only remove extensions which are named overlay-ext.[version] so as not to mess with other sysexts the user may have
    subprocess.run(f"systemd-sysext unmerge; find {EXT_DEST} -mindepth 1 -maxdepth 1 -name '{BASE_EXT_NAME}.*' -exec rm -rf {{}} +", shell=True)
    exit_message(f"Cleaned up all generated extensions in {EXT_DEST}")

# Otherwise, we need to be passed a script
if args.script is None:
    exit_message("Error: Must pass a script to be run in order to build overlays.")

# Do not allow running by an unpriveliged user as root is required for commands such as "bootc status"
user = subprocess.check_output("whoami", shell=True).decode(ENCODING_TYPE).strip("\n")
if user != "root":
    exit_message("Error: Must be run as root!")


# First we check the script actually exists as a valid file
try:
    script_contents = open(args.script, "r").read()

except FileNotFoundError:
    exit_message(f"Error: File \"{args.script}\" could not be found.")


# Then that bash can execute it
try:
    subprocess.check_output(f"bash -n {args.script}", stderr=subprocess.DEVNULL, shell=True)

except subprocess.CalledProcessError:
    exit_message(f"Error: File \"{args.script}\" is not a valid bash script - use \"bash -n {args.script}\" to validate it.")


# Check bootc status so we can find the verity hashes of the images
bootc_status = json.loads(subprocess.check_output("bootc status --json", shell=True))
images = None

# Look for the list of images
if STATUS in bootc_status:
    images = bootc_status[STATUS]

else:
    invalid_format(bootc_status, STATUS)


build_for_deployment(images, BOOTED, error_on_no_exist=True, force=args.force)
build_for_deployment(images, STAGED, error_on_no_exist=False, force=True)
